### ISSUE TITLE
Cannot import Classes

### ISSUE THREAD

**Issue by ingvictoriano** [pdrogfer/MidiDroid#12]
Hi! I'm creating a new Android Studio project and adding the latest version of the library, but the classes don't seem to be importing. 

To reproduce
1. Create new Android Studio project
2. Add MidiDroid dependency and Sync 
3. Can't import any Class from MidiDroid

Checking the gradle cache folder only the MidiDroid-v1.2.5.pom file is downloaded there is no .jar or .aar file

Am I doing something wrong, or is it the library  ? Could you check it out  ? 

Thank you for your time!

**Comment by pdrogfer** [comment]
thanks will have a look

**Comment by pdrogfer** [comment]
Resolved. New version v1.3
