### ISSUE TITLE
MidiTrack.insertNote inserts two NoteOn events

### ISSUE THREAD

**Issue by babua** [pdrogfer/MidiDroid#2]
In MidiTrack.java , line 164 

```
public void insertNote(int channel, int pitch, int velocity, long tick, long duration)
    {

        insertEvent(new NoteOn(tick, channel, pitch, velocity));
        insertEvent(new NoteOn(tick + duration, channel, pitch, 0));
    }
```

I think the second inserted event should be a NoteOff.

Cheers

**Comment by pdrogfer** [comment]
a note off message is essentially the same as a note on, with velocity = 0. But I agree it makes more sense. Can you make a pull request? just to keep track of it

**Comment by babua** [comment]
Done, thank you 👍
