### ISSUE TITLE
Build failed. See the log at jitpack.io

### ISSUE THREAD

**Issue by ingvictoriano** [pdrogfer/MidiDroid#6]
Hi! I'm trying to add this project as dependency on my project but I'm getting a Build failed error from jitpack. 

https://jitpack.io/com/github/pdrogfer/MidiDroid/v1.2/MidiDroid-v1.2.pom

https://jitpack.io/com/github/pdrogfer/MidiDroid/v1.2/build.log

Could you please check it out?

Thank you for this library it's really helpful! :)

**Comment by pdrogfer** [comment]
Thanks, haven't updated the library in a while, will see to fix it asap.

**Comment by pdrogfer** [comment]
Closing this. I was able to fix the project configuration, the latest build is ok.

**Comment by ingvictoriano** [comment]
Wow, that was fast. Thank you so much!
